### ISSUE TITLE
Gets buggy with better third person

### ISSUE THREAD

**Issue by kappagaren58** [pitbox46/HorseCombatControls#10]
The mod with better third person combined gets buggy. The better third person's third person horse controls and this mods horse controls doesnt get along so that makes stopping the horse impossible when in third person and the smooth turning gets broken while using better third person. As a modder, i thought you could get in touch with the better third person mod's creator and solve this issue.

**Comment by Tapacywka** [comment]
Is this error relevant at this point in time?

**Comment by pitbox46** [comment]
> Is this error relevant at this point in time?

I'm not sure. I haven't gotten around to testing this. I would guess it's less of a problem in 1.20 because I had to rework the code a little bit

**Comment by Tapacywka** [comment]
> I'm not sure. I haven't gotten around to testing this. I would guess it's less of a problem in 1.20 because I had to rework the code a little bit

Then I'll check it out in a couple hours and report back in case.

**Comment by pitbox46** [comment]
This will not be fixed. Unfortunately Better Third Person is licensed as All Rights Reserved and it is closed source. Because of this, I cannot make my mod compatible. However, I am working on my own independent third person mod
