### ISSUE TITLE
Apparent incompatibility with AstikorCarts

### ISSUE THREAD

**Issue by FlameyFaucet** [pitbox46/HorseCombatControls#2]
Hello. I'd like to report a potential incompatibility with the mod AstikorCarts
There were actually three horse mods in play with the crash, this mod, AstikorCarts, and Realistic Horse Genetics. However, i am certain only Carts and this mod are the cause.
So i tried carrying a carriage from the mod when suddenly the game crashed with a ticking entity error.
If it's worth noting, the horse is from the aforementioned Realistic Horse Genetics mod. Though, that mod and combat controls worked perfectly fine together.
Crash Report: https://pastebin.com/HkCTHnsL
If you think this was caused by another mod, please inform me and i'll head straight to their issue tracker instead. Thanks.

Edit: Removing Horse combat controls fixed the issue, and i am able to load back in the world.

**Comment by pitbox46** [comment]
Should be fixed in the next release. Open another issue if there are still bugs.
