### ISSUE TITLE
[suggestion] config to hold key

### ISSUE THREAD

**Issue by k1r0s** [pitbox46/HorseCombatControls#4]
Rather than switching between modes

**Comment by pitbox46** [comment]
I will likely not implement this unless there is more demand for it.

**Comment by SstarLit** [comment]
i would want this, with the option to invert the setting and have to hold the key to return to vanilla movement, 

separately i'd more want a setting to make the controls toggle only work when actually on a horse, as i found that binding the toggle to ctrl worked best except that's commonly used when not on horseback. it switches between the horse controls when dismounted and makes getting on a horse feel inconsistent.

perhaps this issue could be reopened, with my separate suggestion considered?
