### ISSUE TITLE
Spam in the Server Logs

### ISSUE THREAD

**Issue by kappagaren58** [pitbox46/HorseCombatControls#5]
![image](https://user-images.githubusercontent.com/66776384/149634105-a41f0baa-3c55-4da2-8f3a-2e7859f07fd9.png)
im using 1.16.5 mohist server with plugins 
theres no problem other than spamming
(it spams more if you got stuck in a ramp)

**Comment by pitbox46** [comment]
I can look into this. It may be one of your plugins though.

**Comment by kappagaren58** [comment]
> I can look into this. It may be one of your plugins though.

i think it is not, i tried without plugins too. Normally it sends this regular but sometimes you get stuck while riding(it is not a big deal you can get out easily by just moving in another way) and when you get stuck it just spams.

**Comment by kappagaren58** [comment]
https://youtu.be/aZOzhSizWqk

**Comment by pitbox46** [comment]
Yikes, I completely forgot about this issue, sorry. There's some sort of desync between server and client. Do you have the mod on both sides? If yes, then do you have the server config option for "cancel_rand_rearing" on or off?

**Comment by kappagaren58** [comment]
Its not a big deal, i also did forget about it since i saw your response in my e-mails. I had it on both sides with forcing the controls enabled from server config. Imma look at your suggestion as soon as i have access to my pc. But does it solve the "getting stuck" issue or did you solve it on newer updates cuz i didn't check it recently.

**Comment by kappagaren58** [comment]
> Its not a big deal, i also did forget about it since i saw your response in my e-mails. I had it on both sides with forcing the controls enabled from server config. Imma look at your suggestion as soon as i have access to my pc. But does it solve the "getting stuck" issue or did you solve it on newer updates cuz i didn't check it recently.

I will get back to you after i try. I can give the logs if you want too.
